# version: '3.8'

services:

  node:
    build: 
      context: ./node
      dockerfile: Dockerfile.local
    container_name: node-app
    image: lucasfmartins/node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - app-network
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx-proxy
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   restart: always
  #   ports:
  #     - "9000:80"
  #   depends_on:
  #     - node
  #   networks:
  #     - app-network

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: lucasfmartins/nginx:prod
    container_name: nginx
    networks: 
      - app-network
    ports: 
      - "9000:80"
    depends_on:
      - node
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=people_db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

networks: 
  app-network:
    driver: bridge
