# version: '3.8'

services:

  node-app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    container_name: node-app
    networks:
      - app-network
    tty: true
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    depends_on:
      - mysql-db

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    networks: 
      - app-network
    ports: 
      - "8080:8080"
    depends_on:
      - node-app
  
  mysql-db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql-db
    restart: always
    tty: true
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

networks: 
  app-network:
    driver: bridge
